name: SkyMarket
version: '${version}'
main: com.github.lukesky19.skymarket.SkyMarket
api-version: '1.21'
load: STARTUP
author: lukeskywlker19
description: A rotating shop plugin
depend: [Vault, PlaceholderAPI]

commands:
  skymarket:
    description: The base command.
    aliases:
      - sm
      - skm
      - market
      - blackmarket
      - bm
permissions:
  skymarket.commands.skymarket:
    description: Permission to access the shop.
    default: op
  skyshop.commands.skymarket.reload:
    description: Permission to reload the plugin.
    default: op