config-version: 2.0.0
locale: en_US
# These can and will only be registered when the plugin is first enabled.
aliases:
    -
        alias: "vm"
        market-id: "villagers"
    -
        alias: "villagers"
        market-id: "villagers"
    -
        alias: "villagermarket"
        market-id: "villagers"
    -
        alias: "sm"
        market-id: "skymarket"
    -
        alias: "skymarket"
        market-id: "skymarket"
